import React from "react";

export const metadata = {
  title: 'Home fight',
  description: 'Generated by Aquillae',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Monument+Extended:wght@100&display=swap" />
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
        <style>
          {`
            body {
              font-family: 'Monument Extended', sans-serif;
              font-weight: 100; /* Ajuste o valor conforme necessário (pode variar entre 100 e 900) */
            }
          `}
        </style>
      </head>

      <body>
        {children}
      </body>
    </html>
  );
}
